[package]
name = "common-utils"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.5.1"
serde = { version = "1.0.202", features = ["derive"] }
strum = "0.26.2"
strum_macros = "0.26.2"
